# Default Configuration-File for Sudo 

# Decide if this plugin runs on a proxy (BungeeCord)
bungeecord: true

# commands which require sudo (only necessary when bungeecord is disabled)
required:
- 'op'
- 'end'
- 'stop'
- 'gamemode'