# Default Configuration File for Sudo

netty:
  # port of the socket-server which runs on background
  # do NOT choose a used port
  port: 10020
  
sudo:
  # maximum attempts after lock
  maxAttempts: 3
  # lock users after to many attempts
  lock: true
  
  # blocked permissions
  permissions:
  - 'minecraft.command.stop'
  - 'minecraft.command.gamemode'
  - 'bukkit.command.reload'
  - 'bukkit.command.reload'
  - 'bukkit.command.timings'