# Default Configuration-File for Sudo

# Only Bukkit
bungeecord:
  # Enter uuid from stats field in bungeecords config.yml
  uuid: 
  # Enter the IP of the BungeeCord
  host: 'localhost'
  # Enter the port of BungeeCords Sudo Socket-Server
  port: 10020
  
  # enter how many times a bukkit server attempts to reconnect after losing connection (negative numbers for infinite)
  reconnect: 10

sudo:
  # maximum attempts after lock
  maxAttempts: 3
  # lock users after to many attempts
  lock: true
  
  # blocked permissions
  permissions:
  - 'minecraft.command.stop'
  - 'minecraft.command.gamemode'
  - 'bukkit.command.reload'
  - 'bukkit.command.reload'
  - 'bukkit.command.timings'